apiVersion: v1
kind: Pod
metadata:
  namespace: production
  name: simple-webapp-blue
  labels:
    app: web
spec:
  containers:
  - name: web-blue
    image: mmumshad/simple-webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: blue