apiVersion: v1
kind: Pod
metadata:
  namespace: production
  name: simple-webapp-red
  labels:
    app: web
spec:
  containers:
  - name: web-red
    image: mmumshad/simple-webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: red