apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: service-nodeport-web
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 8080
    targetPort: 8080
    NodePort: 30008